name: 'Release Uclusion'
description: 'Label Uclusion jobs from release'
branding:
  icon: 'tag'
  color: 'green'
inputs:
  secret_key_id:
    description: 'Uclusion secret key id'
    required: true
  secret_key:
    description: 'Uclusion secret key'
    required: true
  workspace_id:
    description: 'Uclusion workspace id'
    required: true
  git_token:
    description: 'Github token'
    required: true
  git-sha:
    description: 'The field github.sha associated with commits with Uclusion job codes'
    required: true
  git-repository:
    description: 'The field github.repository which returns owner/repo-name'
    required: true
  label:
    description: 'Label to apply to jobs listed in the release commits.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.secret_key_id }}
    - ${{ inputs.secret_key }}
    - ${{ inputs.workspace_id }}
    - ${{ inputs.git_token }}
    - ${{ inputs.git-sha }}
    - ${{ inputs.git-repository }}
    - ${{ inputs.label }}
